package constants

const (
	DEFAULT_SERVER_IP_ADDRESS = ""
	DEFAULT_SERVER_PORT       = 443
)

const (
	DEFAULT_H1_SERVER_IP_ADDRESS = ""
	DEFAULT_H1_SERVER_PORT       = 443
)

const (
	DEFAULT_MCP_SERVER_IP_ADDRESS = ""
	DEFAULT_MCP_SERVER_PORT       = 4432
)
